export type Stage = 'idea' | 'shoot' | 'edit' | 'posted'
export type Item = { id: string; hook: string; shots: string[]; keyword?: string; caption?: string; stage: Stage; day?: string; postedAt?: string; createdAt: string }
export type Ref = { id: string; url: string; note: string; createdAt: string }
export type Board = { items: Item[]; refs: Ref[]; hooks: string[] }

const script = String.raw`(() => {
  const root = document.currentScript.closest('[data-reels]'), $ = s => root.querySelector(s);
  const el = (tag, text, cls) => { const n = document.createElement(tag); if(text != null) n.textContent = text; if(cls) n.className = cls; return n; };
  const button = (text, fn, cls = 'tool-button') => { const b = el('button', text, cls); b.type = 'button'; b.addEventListener('click', fn); return b; };
  const labels = {idea:'靈感',shoot:'待拍',edit:'剪緊',posted:'已出'}, stages = Object.keys(labels);
  let board, timer, revision = 0, saving = false, savedRevision = 0, active = 'overview';
  const status = $('[data-save]');
  const request = async (url, options) => { const r = await fetch(url, options); const d = await r.json(); if(!r.ok) throw new Error(d.error || '伺服器回應 ' + r.status); return d; };
  const json = (method, body) => ({method, headers:{'content-type':'application/json'}, body:JSON.stringify(body)});
  const validBoard = d => d && Array.isArray(d.items) && Array.isArray(d.refs) && Array.isArray(d.hooks);
  const save = async () => {
    if(saving || savedRevision === revision) return;
    saving = true; const version = revision; status.textContent = '儲存緊…';
    try { const d = await request('/cms/api/board', json('PUT', board)); if(!validBoard(d)) throw new Error('回傳資料唔齊'); savedRevision = version; status.textContent = version === revision ? '已儲存' : '等緊儲存…'; }
    catch(e) { status.textContent = '儲存失敗：' + e.message + '。撳「再儲存」重試。'; }
    finally { saving = false; if(revision > version) { clearTimeout(timer); timer = setTimeout(save, 600); } }
  };
  const change = (rerender = true) => { revision++; status.textContent = '等緊儲存…'; clearTimeout(timer); timer = setTimeout(save, 600); if(rerender) render(); };
  const dayKey = d => d.getFullYear() + '-' + String(d.getMonth()+1).padStart(2,'0') + '-' + String(d.getDate()).padStart(2,'0');
  const startDay = d => new Date(d.getFullYear(), d.getMonth(), d.getDate());
  const addDays = (d, n) => { const x = new Date(d); x.setDate(x.getDate()+n); return x; };
  const days = () => Array.from({length:7}, (_,i) => addDays(startDay(new Date()), i));
  const pill = item => button(labels[item.stage] || '靈感', () => { item.stage = stages[(stages.indexOf(item.stage)+1)%4]; if(item.stage === 'posted') item.postedAt = new Date().toISOString(); change(); }, 'rs-pill rs-' + item.stage);
  const empty = (box, text) => box.append(el('p', text, 'tool-empty'));
  const dateSelect = item => { const s = el('select'); s.setAttribute('aria-label', '排期：' + item.hook); const opts = [['','未排期'],...days().map(d=>[dayKey(d),d.toLocaleDateString('zh-HK',{month:'numeric',day:'numeric',weekday:'short'})])]; if(item.day && !opts.some(o=>o[0]===item.day)) opts.push([item.day,item.day]); opts.forEach(([v,t])=>{const o=el('option',t);o.value=v;s.append(o);});s.value=item.day||'';s.addEventListener('change',()=>{if(s.value)item.day=s.value;else delete item.day;change();});return s; };
  const overview = () => {
    const box = $('[data-overview]'); box.replaceChildren(); const now = new Date(), monday = startDay(now); monday.setDate(monday.getDate()-((monday.getDay()+6)%7));
    const weeks = Array.from({length:8},(_,i)=>{const from=addDays(monday,(i-7)*7),to=addDays(from,7);return {from,count:board.items.filter(x=>{const t=Date.parse(x.postedAt||'');return x.stage==='posted'&&t>=from.getTime()&&t<to.getTime();}).length};});
    box.append(el('h2','每週出片'),el('p','最近 8 週 · 紅色係未出片嗰週','tool-muted'));const chart=el('div',null,'rs-chart'),max=Math.max(1,...weeks.map(w=>w.count));
    weeks.forEach(w=>{const col=el('div',null,'rs-chart-col');col.setAttribute('aria-label',dayKey(w.from)+' 嗰週：'+w.count+' 條');col.append(el('strong',String(w.count)));const track=el('div',null,'rs-chart-track'),bar=el('div',null,'rs-chart-bar'+(!w.count?' rs-zero':''));bar.style.height=Math.max(4,w.count/max*100)+'%';track.append(bar);col.append(track,el('small',(w.from.getMonth()+1)+'/'+w.from.getDate()));chart.append(col);});box.append(chart);
    const stats=el('div',null,'rs-stats');[['靈感',board.items.filter(x=>x.stage==='idea').length],['待拍',board.items.filter(x=>x.stage==='shoot').length],['剪緊',board.items.filter(x=>x.stage==='edit').length],['本月已出',board.items.filter(x=>{const d=new Date(x.postedAt||'');return x.stage==='posted'&&d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth();}).length]].forEach(([label,n])=>{const c=el('div');c.append(el('strong',String(n)),el('span',label));stats.append(c);});box.append(stats);
  };
  const week = () => {const box=$('[data-week]');box.replaceChildren();const line=el('section',null,'rs-unscheduled');line.append(el('h2','未排期'));const card=(item)=>{const c=el('article',null,'rs-week-item');c.append(el('strong',item.hook),pill(item),dateSelect(item));return c;};const loose=board.items.filter(x=>!x.day);if(!loose.length)empty(line,'全部排好期喇。');loose.forEach(x=>line.append(card(x)));box.append(line);const grid=el('div',null,'rs-week-grid');days().forEach(d=>{const c=el('section',null,'rs-day');c.append(el('h3',d.toLocaleDateString('zh-HK',{month:'numeric',day:'numeric',weekday:'short'})));const items=board.items.filter(x=>x.day===dayKey(d));if(!items.length)empty(c,'留白都得');items.forEach(x=>c.append(card(x)));grid.append(c);});box.append(grid);};
  const queue = () => {const body=$('[data-queue]');body.replaceChildren();board.items.forEach((item,i)=>{const tr=el('tr');tr.append(el('td',String(i+1)));[['hook',item.hook],['shots',item.shots.join('\n')]].forEach(([key,value])=>{const td=el('td'),edit=el('div',value,'rs-edit');edit.contentEditable='true';edit.setAttribute('role','textbox');edit.setAttribute('aria-label',(key==='hook'?'Hook':'Shot list')+' 第 '+(i+1)+' 條');edit.setAttribute('aria-multiline',String(key==='shots'));edit.addEventListener('input',()=>{const text=edit.innerText.replace(/\r/g,'');item[key]=key==='shots'?text.split('\n').map(x=>x.trim()).filter(Boolean):text.trim();change(false);});edit.addEventListener('paste',e=>{e.preventDefault();const text=e.clipboardData.getData('text/plain');const selection=window.getSelection();if(selection&&selection.rangeCount){const range=selection.getRangeAt(0);range.deleteContents();const node=document.createTextNode(text);range.insertNode(node);range.setStartAfter(node);range.collapse(true);selection.removeAllRanges();selection.addRange(range);edit.dispatchEvent(new Event('input'));}});td.append(edit);tr.append(td);});const stage=el('td');stage.append(pill(item));const del=el('td');del.append(button('刪',()=>{if(confirm('刪咗呢條 Reel？')){board.items=board.items.filter(x=>x.id!==item.id);change();}},'rs-delete'));tr.append(stage,del);body.append(tr);});};
  const refs = () => {const box=$('[data-refs]');box.replaceChildren();if(!board.refs.length)empty(box,'見到想學嘅拍法，就貼落嚟。');board.refs.forEach(ref=>{const card=el('article',null,'rs-ref');let url;try{url=new URL(ref.url);}catch{}const host=url?url.hostname.replace(/^www\./,''):'';const badge=host==='instagram.com'||host.endsWith('.instagram.com')?'IG':host==='tiktok.com'||host.endsWith('.tiktok.com')?'TT':host==='youtu.be'||host==='youtube.com'||host.endsWith('.youtube.com')?'YT':'↗';card.append(el('b',badge,'rs-domain'),el('p',ref.note||host));if(url&&['http:','https:'].includes(url.protocol)){const a=el('a','開連結 ↗');a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';card.append(a);}card.append(button('刪',()=>{board.refs=board.refs.filter(x=>x.id!==ref.id);change();},'rs-delete'));box.append(card);});};
  const hooks = () => {const box=$('[data-hooks]');box.replaceChildren();if(!board.hooks.length)empty(box,'加一句下次拍片想用嘅開頭。');board.hooks.forEach((hook,i)=>{const c=el('article',null,'rs-hook');c.append(el('p',hook),button('複製',async e=>{const b=e.currentTarget;try{await navigator.clipboard.writeText(hook);b.textContent='已複製';}catch{$('[data-notice]').textContent='複製唔到，揀句字手動複製先。';}}),button('刪',()=>{board.hooks.splice(i,1);change();},'rs-delete'));box.append(c);});};
  const render = () => {if(!board)return;({overview,week,queue,refs,hooks}[active]||(()=>{}))();};
  root.querySelectorAll('[data-reel-tab]').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.reelTab;root.querySelectorAll('[data-reel-tab]').forEach(x=>{x.setAttribute('aria-selected',String(x===b));x.tabIndex=x===b?0:-1;});root.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==active);render();}));
  $('[data-tabs]').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const tabs=[...root.querySelectorAll('[data-reel-tab]')],i=tabs.indexOf(document.activeElement),n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[n].click();tabs[n].focus();});
  const newItem = values => ({id:crypto.randomUUID(),hook:'新 Reel：撳呢度改開頭',shots:[],stage:'idea',createdAt:new Date().toISOString(),...values});
  $('[data-add-item]').addEventListener('click',()=>{board.items.push(newItem({}));change();});
  $('[data-idea-form]').addEventListener('submit',async e=>{e.preventDefault();const what=$('[name=what]').value.trim(),place=$('[name=place]').value.trim(),out=$('[data-ideas]'),b=e.target.querySelector('button');if(!what)return;b.disabled=true;out.replaceChildren(el('p','諗緊三條 Reel…'));try{const d=await request('/cms/api/reel-ideas',json('POST',{what,place:place||undefined}));if(!Array.isArray(d.ideas)||!d.ideas.length||d.ideas.some(x=>typeof x.hook!=='string'||!Array.isArray(x.shots)||typeof x.caption!=='string'))throw new Error('回傳資料唔齊');out.replaceChildren();d.ideas.slice(0,3).forEach(idea=>{const c=el('article',null,'rs-idea');c.append(el('h2',idea.hook));const list=el('ol');idea.shots.forEach(s=>list.append(el('li',s)));c.append(list,el('span','留言：'+(idea.keyword||'未設定'),'tool-chip'),el('p',idea.caption,'rs-caption'));c.append(button('加入排程',event=>{board.items.push(newItem({hook:idea.hook,shots:[...idea.shots],keyword:idea.keyword,caption:idea.caption}));change();event.currentTarget.disabled=true;event.currentTarget.textContent='已加入排程';$('[data-notice]').textContent='已加入排程';}));out.append(c);});}catch(err){out.replaceChildren(el('p','諗 idea 失敗：'+err.message,'tool-error'));}finally{b.disabled=false;}});
  $('[data-ref-form]').addEventListener('submit',e=>{e.preventDefault();const input=$('[name=refUrl]'),note=$('[name=refNote]');try{const u=new URL(input.value.trim());if(!['http:','https:'].includes(u.protocol))throw new Error('請貼 http 或 https 連結');board.refs.push({id:crypto.randomUUID(),url:u.href,note:note.value.trim(),createdAt:new Date().toISOString()});input.value='';note.value='';$('[data-ref-error]').textContent='';change();}catch(err){$('[data-ref-error]').textContent='連結唔啱，請貼完整網址。';}});
  $('[data-hook-form]').addEventListener('submit',e=>{e.preventDefault();const input=$('[name=hook]');if(input.value.trim()){board.hooks.push(input.value.trim());input.value='';change();}});
  $('[data-retry-save]').addEventListener('click',()=>{clearTimeout(timer);save();});
  window.addEventListener('beforeunload',e=>{if(revision!==savedRevision){e.preventDefault();e.returnValue='';}});
  const load = async () => {const b=$('[data-load]');b.disabled=true;status.textContent='載入緊企劃板…';try{const d=await request('/cms/api/board');if(!validBoard(d))throw new Error('回傳資料唔齊');board=d;$('[data-board]').hidden=false;render();status.textContent='已儲存';b.hidden=true;}catch(err){status.textContent='企劃板載入失敗：'+err.message;b.hidden=false;}finally{b.disabled=false;}};
  $('[data-load]').addEventListener('click',load);load();
})();`

const tabs = [['overview','總覽'],['ideas','諗 idea'],['week','本週'],['queue','排程'],['refs','參考'],['hooks','Hooks']] as const
export const ReelStudio = () => <div class="rs" data-reels=""><link rel="stylesheet" href="/cms/kit/dev.css" /><link rel="stylesheet" href="/cms/kit/tools.css" /><link rel="stylesheet" href="/cms/kit/app.css" /><h1>Reel 企劃板</h1><p class="rs-lead">影咗嘅嘢唔好淨係留喺相簿。記低開頭、要拍嘅鏡頭，再排好今週出片。</p><div class="rs-save"><span data-save="" role="status"></span><button type="button" class="rs-delete" data-retry-save="">再儲存</button><button type="button" class="tool-button" data-load="">重新載入</button></div><div data-board="" hidden><div class="rs-tabs" role="tablist" aria-label="Reel 企劃板" data-tabs="">{tabs.map(([id,label],i)=><button type="button" role="tab" id={`reel-tab-${id}`} aria-controls={`reel-panel-${id}`} aria-selected={i===0?'true':'false'} tabindex={i===0?0:-1} data-reel-tab={id}>{label}</button>)}</div><p class="tool-muted" data-notice="" role="status"></p>{tabs.map(([id])=><section role="tabpanel" id={`reel-panel-${id}`} aria-labelledby={`reel-tab-${id}`} data-panel={id} hidden={id!=='overview'}>{id==='overview'?<div data-overview="" />:id==='ideas'?<><form class="rs-form" data-idea-form=""><label>今日影咗咩／去咗邊？<textarea name="what" rows={4} required placeholder="例如：喺福岡食咗間街坊拉麵，仲拍咗排隊同落單過程" /></label><label>地點<input name="place" placeholder="例如：福岡天神" /></label><button class="tool-button" type="submit">諗三條 Reel</button></form><div class="rs-ideas" data-ideas="" aria-live="polite" /></>:id==='week'?<div data-week="" />:id==='queue'?<><p class="tool-muted">撳字就改得；撳進度會跳去下一步。Shot list 每行一個鏡頭。</p><div class="rs-table-scroll" tabindex={0} role="region" aria-label="Reel 排程，可以左右捲"><table class="rs-table"><thead><tr><th>#</th><th>Hook</th><th>Shot list</th><th>進度</th><th><span class="rs-sr">刪除</span></th></tr></thead><tbody data-queue="" /></table></div><button type="button" class="rs-add" data-add-item="">＋ 新增</button></>:id==='refs'?<><form class="rs-form" data-ref-form=""><label>IG／TikTok／YouTube 連結<input name="refUrl" type="url" required placeholder="https://…" /></label><label>一句筆記<input name="refNote" placeholder="想學佢點樣開場、轉鏡？" /></label><button class="tool-button" type="submit">加入參考</button><p class="tool-error" data-ref-error="" role="status" /></form><div class="tool-stack" data-refs="" /></>:<><p class="tool-muted">頭幾條係由你自己 Reels 嘅開頭整理。</p><form class="rs-inline-form" data-hook-form=""><input name="hook" required aria-label="新 Hook" placeholder="記低一句想用嘅開頭" /><button class="tool-button" type="submit">加入</button></form><div class="tool-stack" data-hooks="" /></>}</section>)}</div><script dangerouslySetInnerHTML={{__html:script}} /></div>
